/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "cont1.v:1" *)
module cont1(Q, RCO, clk, enb, modo, D);
  (* src = "cont1.v:23" *)
  wire [3:0] _000_;
  (* src = "cont1.v:23" *)
  wire _001_;
  (* src = "cont1.v:23" *)
  wire _002_;
  (* src = "cont1.v:23" *)
  wire _003_;
  (* src = "cont1.v:23" *)
  wire _004_;
  (* src = "cont1.v:28" *)
  (* unused_bits = "4" *)
  wire [31:0] _005_;
  wire [1:0] _006_;
  wire [1:0] _007_;
  wire [1:0] _008_;
  wire [1:0] _009_;
  wire [1:0] _010_;
  wire [1:0] _011_;
  wire [1:0] _012_;
  wire [1:0] _013_;
  wire [1:0] _014_;
  wire _015_;
  wire _016_;
  wire [3:0] _017_;
  wire [1:0] _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  (* src = "cont1.v:50" *)
  wire _025_;
  (* src = "cont1.v:50" *)
  wire _026_;
  (* src = "cont1.v:56" *)
  wire _027_;
  (* src = "cont1.v:56" *)
  wire _028_;
  (* src = "cont1.v:65" *)
  wire _029_;
  (* src = "cont1.v:65" *)
  wire _030_;
  (* src = "cont1.v:65" *)
  wire _031_;
  (* src = "cont1.v:50" *)
  wire _032_;
  (* src = "cont1.v:56" *)
  wire _033_;
  (* src = "cont1.v:65" *)
  wire _034_;
  (* src = "cont1.v:65" *)
  wire _035_;
  (* src = "cont1.v:31|cont1.v:27|<techmap.v>:432" *)
  wire [15:0] _036_;
  (* src = "cont1.v:31|cont1.v:27|<techmap.v>:428" *)
  wire [3:0] _037_;
  wire [3:0] _038_;
  wire _039_;
  (* src = "cont1.v:29" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _040_;
  (* src = "cont1.v:30" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _041_;
  (* src = "cont1.v:28|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "3" *)
  wire [31:0] _042_;
  (* src = "cont1.v:31|cont1.v:27|<techmap.v>:445" *)
  wire _043_;
  (* src = "cont1.v:29|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _044_;
  (* src = "cont1.v:30|cont1.v:29|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _045_;
  (* src = "cont1.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _046_;
  (* src = "cont1.v:29|<techmap.v>:260|<techmap.v>:229" *)
  wire _047_;
  (* src = "cont1.v:30|cont1.v:29|<techmap.v>:260|<techmap.v>:229" *)
  wire _048_;
  (* src = "cont1.v:13" *)
  input [3:0] D;
  (* src = "cont1.v:16" *)
  output [3:0] Q;
  reg [3:0] Q;
  (* src = "cont1.v:17" *)
  output RCO;
  reg RCO;
  (* src = "cont1.v:12" *)
  input clk;
  (* src = "cont1.v:12" *)
  input enb;
  (* src = "cont1.v:14" *)
  input [1:0] modo;
  assign _006_[0] = _005_[0] |(* src = "cont1.v:50" *)  _017_[1];
  assign _006_[1] = _017_[2] |(* src = "cont1.v:50" *)  _017_[3];
  assign _019_ = _006_[0] |(* src = "cont1.v:50" *)  _006_[1];
  assign _007_[0] = _005_[0] |(* src = "cont1.v:65" *)  Q[1];
  assign _020_ = _007_[0] |(* src = "cont1.v:65" *)  _007_[1];
  assign _008_[0] = Q[0] |(* src = "cont1.v:65" *)  _017_[1];
  assign _007_[1] = Q[2] |(* src = "cont1.v:65" *)  Q[3];
  assign _021_ = _008_[0] |(* src = "cont1.v:65" *)  _007_[1];
  assign _022_ = _018_[0] |(* src = "cont1.v:31|cont1.v:27" *)  _018_[1];
  assign _023_ = modo[0] |(* src = "cont1.v:30|cont1.v:27" *)  _018_[1];
  assign _024_ = _018_[0] |(* src = "cont1.v:29|cont1.v:27" *)  modo[1];
  assign _009_[0] = _036_[1] |(* src = "cont1.v:31|cont1.v:27|<techmap.v>:441" *)  _036_[5];
  assign _009_[1] = _036_[9] |(* src = "cont1.v:31|cont1.v:27|<techmap.v>:441" *)  _036_[13];
  assign _037_[1] = _009_[0] |(* src = "cont1.v:31|cont1.v:27|<techmap.v>:441" *)  _009_[1];
  assign _010_[0] = _036_[3] |(* src = "cont1.v:31|cont1.v:27|<techmap.v>:441" *)  _036_[7];
  assign _010_[1] = _036_[11] |(* src = "cont1.v:31|cont1.v:27|<techmap.v>:441" *)  _036_[15];
  assign _037_[3] = _010_[0] |(* src = "cont1.v:31|cont1.v:27|<techmap.v>:441" *)  _010_[1];
  assign _011_[0] = _036_[2] |(* src = "cont1.v:31|cont1.v:27|<techmap.v>:441" *)  _036_[6];
  assign _011_[1] = _036_[10] |(* src = "cont1.v:31|cont1.v:27|<techmap.v>:441" *)  _036_[14];
  assign _037_[2] = _011_[0] |(* src = "cont1.v:31|cont1.v:27|<techmap.v>:441" *)  _011_[1];
  assign _012_[0] = _036_[0] |(* src = "cont1.v:31|cont1.v:27|<techmap.v>:441" *)  _036_[4];
  assign _012_[1] = _036_[8] |(* src = "cont1.v:31|cont1.v:27|<techmap.v>:441" *)  _036_[12];
  assign _037_[0] = _012_[0] |(* src = "cont1.v:31|cont1.v:27|<techmap.v>:441" *)  _012_[1];
  assign _013_[0] = _039_ |(* src = "cont1.v:31|cont1.v:27|<techmap.v>:445" *)  _031_;
  assign _013_[1] = _028_ |(* src = "cont1.v:31|cont1.v:27|<techmap.v>:445" *)  _026_;
  assign _043_ = _013_[0] |(* src = "cont1.v:31|cont1.v:27|<techmap.v>:445" *)  _013_[1];
  assign _014_[0] = Q[0] |(* src = "cont1.v:65" *)  Q[1];
  assign _015_ = _014_[0] |(* src = "cont1.v:65" *)  _007_[1];
  assign _016_ = modo[0] |(* src = "cont1.v:28|cont1.v:27" *)  modo[1];
  assign _025_ = ~(* src = "cont1.v:50" *) _019_;
  assign _027_ = ~(* src = "cont1.v:65" *) _015_;
  assign _029_ = ~(* src = "cont1.v:65" *) _020_;
  assign _030_ = ~(* src = "cont1.v:65" *) _021_;
  assign _039_ = ~(* src = "cont1.v:31|cont1.v:27" *) _022_;
  assign _031_ = ~(* src = "cont1.v:30|cont1.v:27" *) _023_;
  assign _028_ = ~(* src = "cont1.v:29|cont1.v:27" *) _024_;
  assign _026_ = ~(* src = "cont1.v:28|cont1.v:27" *) _016_;
  assign _032_ = _025_ &(* src = "cont1.v:50" *)  _026_;
  assign _035_ = _034_ |(* src = "cont1.v:65" *)  _030_;
  assign _033_ = _027_ &(* src = "cont1.v:56" *)  _028_;
  assign _034_ = _027_ |(* src = "cont1.v:65" *)  _029_;
  assign _004_ = _035_ &(* src = "cont1.v:65" *)  _031_;
  assign _003_ = _033_ ? (* src = "cont1.v:56" *) 1'h1 : _004_;
  assign _001_ = enb ? (* src = "cont1.v:24" *) _002_ : RCO;
  assign _002_ = _032_ ? (* src = "cont1.v:50" *) 1'h1 : _003_;
  assign _000_[0] = enb ? (* src = "cont1.v:24" *) _038_[0] : Q[0];
  assign _000_[1] = enb ? (* src = "cont1.v:24" *) _038_[1] : Q[1];
  assign _000_[2] = enb ? (* src = "cont1.v:24" *) _038_[2] : Q[2];
  assign _000_[3] = enb ? (* src = "cont1.v:24" *) _038_[3] : Q[3];
  assign _038_[0] = _043_ ? (* src = "cont1.v:31|cont1.v:27|<techmap.v>:445" *) _037_[0] : 1'hx;
  assign _038_[1] = _043_ ? (* src = "cont1.v:31|cont1.v:27|<techmap.v>:445" *) _037_[1] : 1'hx;
  assign _038_[2] = _043_ ? (* src = "cont1.v:31|cont1.v:27|<techmap.v>:445" *) _037_[2] : 1'hx;
  assign _038_[3] = _043_ ? (* src = "cont1.v:31|cont1.v:27|<techmap.v>:445" *) _037_[3] : 1'hx;
  (* src = "cont1.v:23" *)
  always @(posedge clk)
      Q[0] <= _000_[0];
  (* src = "cont1.v:23" *)
  always @(posedge clk)
      Q[1] <= _000_[1];
  (* src = "cont1.v:23" *)
  always @(posedge clk)
      Q[2] <= _000_[2];
  (* src = "cont1.v:23" *)
  always @(posedge clk)
      Q[3] <= _000_[3];
  (* src = "cont1.v:23" *)
  always @(posedge clk)
      RCO <= _001_;
  assign _042_[1] = Q[1] &(* src = "cont1.v:28|<techmap.v>:260|<techmap.v>:221" *)  Q[0];
  assign _042_[2] = Q[2] &(* src = "cont1.v:28|<techmap.v>:260|<techmap.v>:229" *)  _042_[1];
  assign _046_ = _017_[1] &(* src = "cont1.v:29|<techmap.v>:260|<techmap.v>:221" *)  Q[0];
  assign _047_ = _017_[2] &(* src = "cont1.v:29|<techmap.v>:260|<techmap.v>:229" *)  _044_[1];
  assign _044_[1] = Q[1] |(* src = "cont1.v:29|<techmap.v>:260|<techmap.v>:221" *)  _046_;
  assign _044_[2] = Q[2] |(* src = "cont1.v:29|<techmap.v>:260|<techmap.v>:229" *)  _047_;
  assign _048_ = _017_[2] &(* src = "cont1.v:30|cont1.v:29|<techmap.v>:260|<techmap.v>:229" *)  _042_[1];
  assign _045_[2] = Q[2] |(* src = "cont1.v:30|cont1.v:29|<techmap.v>:260|<techmap.v>:229" *)  _048_;
  assign _018_[1] = modo[1] ^(* src = "cont1.v:30|cont1.v:27" *)  1'h1;
  assign _018_[0] = modo[0] ^(* src = "cont1.v:29|cont1.v:27" *)  1'h1;
  assign _036_[12] = _005_[0] &(* src = "cont1.v:31|cont1.v:27|<techmap.v>:434" *)  _026_;
  assign _036_[13] = _005_[1] &(* src = "cont1.v:31|cont1.v:27|<techmap.v>:434" *)  _026_;
  assign _036_[14] = _005_[2] &(* src = "cont1.v:31|cont1.v:27|<techmap.v>:434" *)  _026_;
  assign _036_[15] = _005_[3] &(* src = "cont1.v:31|cont1.v:27|<techmap.v>:434" *)  _026_;
  assign _036_[8] = _005_[0] &(* src = "cont1.v:31|cont1.v:27|<techmap.v>:434" *)  _028_;
  assign _036_[9] = _040_[1] &(* src = "cont1.v:31|cont1.v:27|<techmap.v>:434" *)  _028_;
  assign _036_[10] = _040_[2] &(* src = "cont1.v:31|cont1.v:27|<techmap.v>:434" *)  _028_;
  assign _036_[11] = _040_[3] &(* src = "cont1.v:31|cont1.v:27|<techmap.v>:434" *)  _028_;
  assign _036_[4] = _005_[0] &(* src = "cont1.v:31|cont1.v:27|<techmap.v>:434" *)  _031_;
  assign _036_[5] = _005_[1] &(* src = "cont1.v:31|cont1.v:27|<techmap.v>:434" *)  _031_;
  assign _036_[6] = _041_[2] &(* src = "cont1.v:31|cont1.v:27|<techmap.v>:434" *)  _031_;
  assign _036_[7] = _041_[3] &(* src = "cont1.v:31|cont1.v:27|<techmap.v>:434" *)  _031_;
  assign _036_[0] = D[0] &(* src = "cont1.v:31|cont1.v:27|<techmap.v>:434" *)  _039_;
  assign _036_[1] = D[1] &(* src = "cont1.v:31|cont1.v:27|<techmap.v>:434" *)  _039_;
  assign _036_[2] = D[2] &(* src = "cont1.v:31|cont1.v:27|<techmap.v>:434" *)  _039_;
  assign _036_[3] = D[3] &(* src = "cont1.v:31|cont1.v:27|<techmap.v>:434" *)  _039_;
  assign _005_[1] = Q[1] ^(* src = "cont1.v:28|<techmap.v>:263" *)  Q[0];
  assign _005_[2] = Q[2] ^(* src = "cont1.v:28|<techmap.v>:263" *)  _042_[1];
  assign _005_[3] = Q[3] ^(* src = "cont1.v:28|<techmap.v>:263" *)  _042_[2];
  assign _040_[1] = _017_[1] ^(* src = "cont1.v:29|<techmap.v>:263" *)  Q[0];
  assign _040_[2] = _017_[2] ^(* src = "cont1.v:29|<techmap.v>:263" *)  _044_[1];
  assign _040_[3] = _017_[3] ^(* src = "cont1.v:29|<techmap.v>:263" *)  _044_[2];
  assign _017_[1] = Q[1] ^(* src = "cont1.v:29|<techmap.v>:262" *)  1'h1;
  assign _017_[2] = Q[2] ^(* src = "cont1.v:29|<techmap.v>:262" *)  1'h1;
  assign _005_[0] = Q[0] ^(* src = "cont1.v:30|cont1.v:29|<techmap.v>:263" *)  1'h1;
  assign _041_[2] = _017_[2] ^(* src = "cont1.v:30|cont1.v:29|<techmap.v>:263" *)  _042_[1];
  assign _041_[3] = _017_[3] ^(* src = "cont1.v:30|cont1.v:29|<techmap.v>:263" *)  _045_[2];
  assign _017_[3] = Q[3] ^(* src = "cont1.v:30|cont1.v:29|<techmap.v>:262" *)  1'h1;
  assign _005_[31:5] = 27'h0000000;
  assign _008_[1] = _007_[1];
  assign _014_[1] = _007_[1];
  assign _017_[0] = _005_[0];
  assign { _040_[30:4], _040_[0] } = { _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _040_[31], _005_[0] };
  assign { _041_[30:4], _041_[1:0] } = { _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _041_[31], _005_[1:0] };
  assign { _042_[31:3], _042_[0] } = { 28'h0000000, _005_[4], Q[0] };
  assign { _044_[30:3], _044_[0] } = { _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], _044_[31], Q[0] };
  assign { _045_[30:3], _045_[1:0] } = { _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _042_[1], Q[0] };
endmodule

(* src = "cont2.v:1" *)
module cont2(Q, RCO, clk, enb, modo, D);
  (* src = "cont2.v:27" *)
  wire [3:0] _000_;
  (* src = "cont2.v:27" *)
  wire _001_;
  (* src = "cont2.v:27" *)
  wire _002_;
  (* src = "cont2.v:27" *)
  wire _003_;
  (* src = "cont2.v:27" *)
  wire _004_;
  (* src = "cont2.v:32" *)
  (* unused_bits = "4" *)
  wire [31:0] _005_;
  wire _006_;
  wire [1:0] _007_;
  wire [1:0] _008_;
  wire [1:0] _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire [1:0] _015_;
  wire _016_;
  wire _017_;
  wire [3:0] _018_;
  wire [1:0] _019_;
  wire [1:0] _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  (* src = "cont2.v:54" *)
  wire _027_;
  (* src = "cont2.v:54" *)
  wire _028_;
  (* src = "cont2.v:60" *)
  wire _029_;
  (* src = "cont2.v:60" *)
  wire _030_;
  (* src = "cont2.v:69" *)
  wire _031_;
  (* src = "cont2.v:69" *)
  wire _032_;
  (* src = "cont2.v:69" *)
  wire _033_;
  (* src = "cont2.v:54" *)
  wire _034_;
  (* src = "cont2.v:60" *)
  wire _035_;
  (* src = "cont2.v:69" *)
  wire _036_;
  (* src = "cont2.v:69" *)
  wire _037_;
  (* src = "cont2.v:35|cont2.v:31|<techmap.v>:432" *)
  wire [11:0] _038_;
  (* src = "cont2.v:35|cont2.v:31|<techmap.v>:428" *)
  wire [3:0] _039_;
  wire [3:0] _040_;
  wire _041_;
  (* src = "cont2.v:33" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _042_;
  (* src = "cont2.v:32|cont1.v:28|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "3" *)
  wire [31:0] _043_;
  (* src = "cont2.v:35|cont2.v:31|<techmap.v>:445" *)
  wire _044_;
  (* src = "cont2.v:34|cont1.v:29|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _045_;
  (* src = "cont2.v:34|cont1.v:29|<techmap.v>:260|<techmap.v>:221" *)
  wire _046_;
  (* src = "cont2.v:34|cont1.v:29|<techmap.v>:260|<techmap.v>:229" *)
  wire _047_;
  (* src = "cont2.v:13" *)
  input [3:0] D;
  (* src = "cont2.v:16" *)
  output [3:0] Q;
  reg [3:0] Q;
  (* init = 1'h0 *)
  (* src = "cont2.v:17" *)
  output RCO;
  reg RCO = 1'h0;
  (* src = "cont2.v:12" *)
  input clk;
  (* src = "cont2.v:12" *)
  input enb;
  (* src = "cont2.v:14" *)
  input [1:0] modo;
  assign _007_[0] = _005_[0] |(* src = "cont2.v:54" *)  _018_[1];
  assign _007_[1] = _018_[2] |(* src = "cont2.v:54" *)  _018_[3];
  assign _021_ = _007_[0] |(* src = "cont2.v:54" *)  _007_[1];
  assign _008_[0] = _005_[0] |(* src = "cont2.v:69" *)  Q[1];
  assign _022_ = _008_[0] |(* src = "cont2.v:69" *)  _008_[1];
  assign _009_[0] = Q[0] |(* src = "cont2.v:69" *)  _018_[1];
  assign _008_[1] = Q[2] |(* src = "cont2.v:69" *)  Q[3];
  assign _023_ = _009_[0] |(* src = "cont2.v:69" *)  _008_[1];
  assign _006_ = _033_ | _030_;
  assign _024_ = _019_[0] |(* src = "cont2.v:33|cont2.v:31" *)  modo[1];
  assign _025_ = _019_[0] |(* src = "cont2.v:35|cont2.v:31" *)  _020_[1];
  assign _026_ = modo[0] |(* src = "cont2.v:34|cont2.v:31" *)  _020_[1];
  assign _010_ = _038_[3] |(* src = "cont2.v:35|cont2.v:31|<techmap.v>:441" *)  _038_[7];
  assign _039_[3] = _010_ |(* src = "cont2.v:35|cont2.v:31|<techmap.v>:441" *)  _038_[11];
  assign _011_ = _038_[2] |(* src = "cont2.v:35|cont2.v:31|<techmap.v>:441" *)  _038_[6];
  assign _039_[2] = _011_ |(* src = "cont2.v:35|cont2.v:31|<techmap.v>:441" *)  _038_[10];
  assign _012_ = _038_[1] |(* src = "cont2.v:35|cont2.v:31|<techmap.v>:441" *)  _038_[5];
  assign _039_[1] = _012_ |(* src = "cont2.v:35|cont2.v:31|<techmap.v>:441" *)  _038_[9];
  assign _013_ = _038_[0] |(* src = "cont2.v:35|cont2.v:31|<techmap.v>:441" *)  _038_[4];
  assign _039_[0] = _013_ |(* src = "cont2.v:35|cont2.v:31|<techmap.v>:441" *)  _038_[8];
  assign _014_ = _041_ |(* src = "cont2.v:35|cont2.v:31|<techmap.v>:445" *)  _006_;
  assign _044_ = _014_ |(* src = "cont2.v:35|cont2.v:31|<techmap.v>:445" *)  _028_;
  assign _015_[0] = Q[0] |(* src = "cont2.v:69" *)  Q[1];
  assign _016_ = _015_[0] |(* src = "cont2.v:69" *)  _008_[1];
  assign _017_ = modo[0] |(* src = "cont2.v:32|cont2.v:31" *)  modo[1];
  assign _027_ = ~(* src = "cont2.v:54" *) _021_;
  assign _029_ = ~(* src = "cont2.v:69" *) _016_;
  assign _031_ = ~(* src = "cont2.v:69" *) _022_;
  assign _032_ = ~(* src = "cont2.v:69" *) _023_;
  assign _030_ = ~(* src = "cont2.v:33|cont2.v:31" *) _024_;
  assign _041_ = ~(* src = "cont2.v:35|cont2.v:31" *) _025_;
  assign _033_ = ~(* src = "cont2.v:34|cont2.v:31" *) _026_;
  assign _028_ = ~(* src = "cont2.v:32|cont2.v:31" *) _017_;
  assign _036_ = _029_ |(* src = "cont2.v:69" *)  _031_;
  assign _034_ = _027_ &(* src = "cont2.v:54" *)  _028_;
  assign _035_ = _029_ &(* src = "cont2.v:60" *)  _030_;
  assign _037_ = _036_ |(* src = "cont2.v:69" *)  _032_;
  assign _004_ = _037_ &(* src = "cont2.v:69" *)  _033_;
  assign _003_ = _035_ ? (* src = "cont2.v:60" *) 1'h1 : _004_;
  assign _001_ = enb ? (* src = "cont2.v:28" *) _002_ : RCO;
  assign _002_ = _034_ ? (* src = "cont2.v:54" *) 1'h1 : _003_;
  assign _000_[0] = enb ? (* src = "cont2.v:28" *) _040_[0] : Q[0];
  assign _000_[1] = enb ? (* src = "cont2.v:28" *) _040_[1] : Q[1];
  assign _000_[2] = enb ? (* src = "cont2.v:28" *) _040_[2] : Q[2];
  assign _000_[3] = enb ? (* src = "cont2.v:28" *) _040_[3] : Q[3];
  assign _040_[0] = _044_ ? (* src = "cont2.v:35|cont2.v:31|<techmap.v>:445" *) _039_[0] : 1'hx;
  assign _040_[1] = _044_ ? (* src = "cont2.v:35|cont2.v:31|<techmap.v>:445" *) _039_[1] : 1'hx;
  assign _040_[2] = _044_ ? (* src = "cont2.v:35|cont2.v:31|<techmap.v>:445" *) _039_[2] : 1'hx;
  assign _040_[3] = _044_ ? (* src = "cont2.v:35|cont2.v:31|<techmap.v>:445" *) _039_[3] : 1'hx;
  (* src = "cont2.v:27" *)
  always @(posedge clk)
      Q[0] <= _000_[0];
  (* src = "cont2.v:27" *)
  always @(posedge clk)
      Q[1] <= _000_[1];
  (* src = "cont2.v:27" *)
  always @(posedge clk)
      Q[2] <= _000_[2];
  (* src = "cont2.v:27" *)
  always @(posedge clk)
      Q[3] <= _000_[3];
  (* src = "cont2.v:27" *)
  always @(posedge clk)
      RCO <= _001_;
  assign _019_[0] = modo[0] ^(* src = "cont2.v:35|cont2.v:31" *)  1'h1;
  assign _020_[1] = modo[1] ^(* src = "cont2.v:34|cont2.v:31" *)  1'h1;
  assign _038_[8] = _005_[0] &(* src = "cont2.v:35|cont2.v:31|<techmap.v>:434" *)  _028_;
  assign _038_[9] = _005_[1] &(* src = "cont2.v:35|cont2.v:31|<techmap.v>:434" *)  _028_;
  assign _038_[10] = _005_[2] &(* src = "cont2.v:35|cont2.v:31|<techmap.v>:434" *)  _028_;
  assign _038_[11] = _005_[3] &(* src = "cont2.v:35|cont2.v:31|<techmap.v>:434" *)  _028_;
  assign _038_[4] = _005_[0] &(* src = "cont2.v:35|cont2.v:31|<techmap.v>:434" *)  _006_;
  assign _038_[5] = _042_[1] &(* src = "cont2.v:35|cont2.v:31|<techmap.v>:434" *)  _006_;
  assign _038_[6] = _042_[2] &(* src = "cont2.v:35|cont2.v:31|<techmap.v>:434" *)  _006_;
  assign _038_[7] = _042_[3] &(* src = "cont2.v:35|cont2.v:31|<techmap.v>:434" *)  _006_;
  assign _038_[0] = D[0] &(* src = "cont2.v:35|cont2.v:31|<techmap.v>:434" *)  _041_;
  assign _038_[1] = D[1] &(* src = "cont2.v:35|cont2.v:31|<techmap.v>:434" *)  _041_;
  assign _038_[2] = D[2] &(* src = "cont2.v:35|cont2.v:31|<techmap.v>:434" *)  _041_;
  assign _038_[3] = D[3] &(* src = "cont2.v:35|cont2.v:31|<techmap.v>:434" *)  _041_;
  assign _018_[1] = Q[1] ^(* src = "cont2.v:34|cont1.v:29|<techmap.v>:262" *)  1'h1;
  assign _018_[2] = Q[2] ^(* src = "cont2.v:34|cont1.v:29|<techmap.v>:262" *)  1'h1;
  assign _018_[3] = Q[3] ^(* src = "cont2.v:34|cont1.v:29|<techmap.v>:262" *)  1'h1;
  assign _005_[0] = Q[0] ^(* src = "cont2.v:34|cont1.v:29|<techmap.v>:263" *)  1'h1;
  assign _042_[1] = _018_[1] ^(* src = "cont2.v:34|cont1.v:29|<techmap.v>:263" *)  Q[0];
  assign _042_[2] = _018_[2] ^(* src = "cont2.v:34|cont1.v:29|<techmap.v>:263" *)  _045_[1];
  assign _042_[3] = _018_[3] ^(* src = "cont2.v:34|cont1.v:29|<techmap.v>:263" *)  _045_[2];
  assign _005_[1] = Q[1] ^(* src = "cont2.v:32|cont1.v:28|<techmap.v>:263" *)  Q[0];
  assign _005_[2] = Q[2] ^(* src = "cont2.v:32|cont1.v:28|<techmap.v>:263" *)  _043_[1];
  assign _005_[3] = Q[3] ^(* src = "cont2.v:32|cont1.v:28|<techmap.v>:263" *)  _043_[2];
  assign _046_ = _018_[1] &(* src = "cont2.v:34|cont1.v:29|<techmap.v>:260|<techmap.v>:221" *)  Q[0];
  assign _047_ = _018_[2] &(* src = "cont2.v:34|cont1.v:29|<techmap.v>:260|<techmap.v>:229" *)  _045_[1];
  assign _045_[1] = Q[1] |(* src = "cont2.v:34|cont1.v:29|<techmap.v>:260|<techmap.v>:221" *)  _046_;
  assign _045_[2] = Q[2] |(* src = "cont2.v:34|cont1.v:29|<techmap.v>:260|<techmap.v>:229" *)  _047_;
  assign _043_[1] = Q[1] &(* src = "cont2.v:32|cont1.v:28|<techmap.v>:260|<techmap.v>:221" *)  Q[0];
  assign _043_[2] = Q[2] &(* src = "cont2.v:32|cont1.v:28|<techmap.v>:260|<techmap.v>:229" *)  _043_[1];
  assign _005_[31:5] = 27'h0000000;
  assign _009_[1] = _008_[1];
  assign _015_[1] = _008_[1];
  assign _018_[0] = _005_[0];
  assign _019_[1] = modo[1];
  assign _020_[0] = _019_[0];
  assign { _042_[30:4], _042_[0] } = { _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _042_[31], _005_[0] };
  assign { _043_[31:3], _043_[0] } = { 28'h0000000, _005_[4], Q[0] };
  assign { _045_[30:3], _045_[0] } = { _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], _045_[31], Q[0] };
endmodule

(* top =  1  *)
(* src = "contador16bits.v:4" *)
module contador16bits(clk, enb, D, modo, Q, RCO);
  wire [1:0] _0_;
  wire _1_;
  (* src = "contador16bits.v:9" *)
  input [15:0] D;
  (* src = "contador16bits.v:11" *)
  output [15:0] Q;
  (* src = "contador16bits.v:12" *)
  output [3:0] RCO;
  (* src = "contador16bits.v:18" *)
  wire a1;
  (* src = "contador16bits.v:19" *)
  wire a2;
  (* src = "contador16bits.v:20" *)
  wire a3;
  (* src = "contador16bits.v:7" *)
  input clk;
  (* src = "contador16bits.v:8" *)
  input enb;
  (* src = "contador16bits.v:10" *)
  input [1:0] modo;
  (* src = "contador16bits.v:16" *)
  wire [15:0] q;
  (* src = "contador16bits.v:17" *)
  wire [3:0] rco1;
  assign _1_ = _0_[0] |(* src = "contador16bits.v:26" *)  _0_[1];
  assign a1 = _1_ ? (* src = "contador16bits.v:27" *) rco1[0] : clk;
  assign a2 = _1_ ? (* src = "contador16bits.v:28" *) rco1[1] : clk;
  assign a3 = _1_ ? (* src = "contador16bits.v:29" *) rco1[2] : clk;
  assign _0_[0] = modo[0] ^(* src = "contador16bits.v:26" *)  1'h1;
  assign _0_[1] = modo[1] ^(* src = "contador16bits.v:26" *)  1'h1;
  (* module_not_derived = 32'd1 *)
  (* src = "contador16bits.v:31" *)
  cont1 U0 (
    .D(D[3:0]),
    .Q(q[3:0]),
    .RCO(rco1[0]),
    .clk(clk),
    .enb(enb),
    .modo(modo)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "contador16bits.v:42" *)
  cont2 U1 (
    .D(D[7:4]),
    .Q(q[7:4]),
    .RCO(rco1[1]),
    .clk(a1),
    .enb(enb),
    .modo(modo)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "contador16bits.v:53" *)
  cont2 U2 (
    .D(D[11:8]),
    .Q(q[11:8]),
    .RCO(rco1[2]),
    .clk(a2),
    .enb(enb),
    .modo(modo)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "contador16bits.v:64" *)
  cont2 U3 (
    .D(D[15:12]),
    .Q(q[15:12]),
    .RCO(rco1[3]),
    .clk(a3),
    .enb(enb),
    .modo(modo)
  );
  assign Q = q;
  assign RCO = rco1;
endmodule
